" Use zsh as shell
set shell=/bin/zsh
set nocompatible              " Use Vim defaults
filetype off

" Set mapleader to comma
let mapleader = ","

" Install Vim-Plug if missing
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Initialize plugin system
call plug#begin('~/.vim/plugged')

" Plugin list
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'Raimondi/delimitMate'
Plug 'preservim/nerdcommenter'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'leafgarland/typescript-vim'

call plug#end()

filetype plugin indent on
syntax on

" General appearance and UI
set number
set relativenumber
set cursorline
set showmatch
set showcmd
set showmode
set ruler
set laststatus=2
set scrolloff=3
set fillchars=vert:\│
set encoding=utf-8
set termguicolors
set clipboard=unnamedplus
set title
set guioptions-=T
set wildmenu
set wildmode=list:longest,full
set ttyfast

" Indentation and formatting
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set smartindent
set copyindent
set shiftround
set smarttab

" Searching
set ignorecase
set smartcase
set hlsearch
set incsearch

" Files and history
set undofile
set history=1000
set undolevels=1000

" Bell
set visualbell
set noerrorbells

" Completion and file ignore
set wildignore=*.bak,*.class,.hg,.git,.svn,*.aux,*.out,*.toc,*.jpg,*.bmp,*.gif,*.png,*.jpeg,*.o,*.obj,*.exe,*.dll,*.manifest,*.spl,*.sw?,*.DS_Store,migrations,*.pyc,*.orig

" Whitespace indicators
set list
set listchars=tab:>·,trail:·,extends:#,nbsp:·

" Paste mode toggle
set pastetoggle=<F2>

" Timeout settings
set timeoutlen=1000
set ttimeoutlen=5

" Keybindings: move/indent lines with Alt
nnoremap <A-k> :m-2<CR>==
nnoremap <A-j> :m+<CR>==
nnoremap <A-h> <<
nnoremap <A-l> >>
nnoremap <silent> <C-l> :nohl<CR><C-l>
inoremap <A-j> <Esc>:m+<CR>==gi
inoremap <A-k> <Esc>:m-2<CR>==gi
inoremap <A-h> <Esc><<`]a
inoremap <A-l> <Esc>>>`]a
vnoremap <A-j> :m'>+<CR>gv=gv
vnoremap <A-k> :m-2<CR>gv=gv
vnoremap <A-h> <gv
vnoremap <A-l> >gv

